export { default as DevInfo } from "./DevInfo";
export { default as Page } from "./Page";
export { default as Skill } from "./Skill";
export { default as Skills } from "./Skills";
export { default as SocialMediaInfo } from "./SocialMediaInfo";
export { default as DevWorkCount } from "./DevWorkCount";
export { default as DevEduTimeline } from "./DevEduTimeline";
export { default as DevEperienceTimeline } from "./DevEperienceTimeline";
export { default as MyProjects } from "./MyProjects";