import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css";

import localFont from "next/font/local";

// import { Vazirmatn } from "next/font/google";

// const vazir = Vazirmatn({
//   subsets: ["arabic", "latin"],
//   display: "swap",
// });
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const vazir = localFont({
  src: "./Vazir.woff2",
  display: "swap",
});
export default function RootLayout({ children }) {
  // throw new Error();
  return (
    <html lang="fa" dir="rtl" className={vazir.className}>
      <body>{children}</body>
    </html>
  );
}
